// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkpev25oCCZnPez_PJEhGpnCOxm11fjg',
    appId: '1:589145493354:web:5ec51abae667ef76595f13',
    messagingSenderId: '589145493354',
    projectId: 'developer-community-app-19742',
    authDomain: 'developer-community-app-19742.firebaseapp.com',
    storageBucket: 'developer-community-app-19742.firebasestorage.app',
    measurementId: 'G-4FEHRX1RK4',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeINyD3lF0Mr-LHebjlFw9Ez-valux3Bw',
    appId: '1:589145493354:android:c394a1ea043cfc5d595f13',
    messagingSenderId: '589145493354',
    projectId: 'developer-community-app-19742',
    storageBucket: 'developer-community-app-19742.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlmLMCXH3vriU8Hvzf4peYiwx42i2FAts',
    appId: '1:589145493354:ios:50490794081a2f87595f13',
    messagingSenderId: '589145493354',
    projectId: 'developer-community-app-19742',
    storageBucket: 'developer-community-app-19742.firebasestorage.app',
    iosBundleId: 'com.example.developerCommunityApp',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlmLMCXH3vriU8Hvzf4peYiwx42i2FAts',
    appId: '1:589145493354:ios:50490794081a2f87595f13',
    messagingSenderId: '589145493354',
    projectId: 'developer-community-app-19742',
    storageBucket: 'developer-community-app-19742.firebasestorage.app',
    iosBundleId: 'com.example.developerCommunityApp',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnkpev25oCCZnPez_PJEhGpnCOxm11fjg',
    appId: '1:589145493354:web:14ff244088b012c8595f13',
    messagingSenderId: '589145493354',
    projectId: 'developer-community-app-19742',
    authDomain: 'developer-community-app-19742.firebaseapp.com',
    storageBucket: 'developer-community-app-19742.firebasestorage.app',
    measurementId: 'G-R5R4N2TJ9T',
  );
}
